THEMES = {
    "Eclipse": {
        "bg_primary":     "#0d0a14",
        "bg_secondary":   "#1a1426",
        "bg_tertiary":    "#241d33",
        "accent":         "#fcc200",
        "purple":         "#4b3b7c",
        "text_primary":   "#e8e8e8",
        "text_secondary": "#9e8fcb",
        "border":         "#3d3356",
        "success":        "#4caf82",
        "danger":         "#e05555",
    },
    "Catppuccin Mocha": {
        "bg_primary":     "#1e1e2e",
        "bg_secondary":   "#181825",
        "bg_tertiary":    "#313244",
        "accent":         "#cba6f7",
        "purple":         "#7c6fa0",
        "text_primary":   "#cdd6f4",
        "text_secondary": "#a6adc8",
        "border":         "#585b70",
        "success":        "#a6e3a1",
        "danger":         "#f38ba8",
    },
    "Celeste": {
        "bg_primary":     "#060a14",
        "bg_secondary":   "#0d1a2e",
        "bg_tertiary":    "#152440",
        "accent":         "#63d4f5",
        "purple":         "#2a6bbf",
        "text_primary":   "#e8f4fd",
        "text_secondary": "#7bafd4",
        "border":         "#2a5080",
        "success":        "#57c9a0",
        "danger":         "#e05555",
    },
"Illusionary": {
    "bg_primary":     "#e8f4ff",
    "bg_secondary":   "#d0e8ff",
    "bg_tertiary":    "#b8d8f8",
    "accent":         "#0066cc",
    "purple":         "#003380",
    "text_primary":   "#030a14",
    "text_secondary": "#2255aa",
    "border":         "#88bbee",
    "success":        "#0066cc",
    "danger":         "#cc2222",
     },  
} 
